---
apiVersion: v1
kind: Namespace
metadata:
  name: demo

# =========================
# oauth2-proxy (GitHub)
# =========================
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth2-proxy-secret
  namespace: demo
type: Opaque
stringData:
  client-id: "Ov23liuVcFs7uWHvLGqP"     # <-- your GitHub OAuth App Client ID
  client-secret: "a1829b1277deafdc26a1d2e7ec1222b8e29f2e76"
  cookie-secret: "6JPi5BWTxaqlgJJLStxhrF5x0Fgojbdxe6IdL9JZczM="  # 32-byte base64

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oauth2-proxy
  template:
    metadata:
      labels:
        app: oauth2-proxy
    spec:
      containers:
      - name: oauth2-proxy
        image: quay.io/oauth2-proxy/oauth2-proxy:v7.6.0
        args:
        - --provider=github
        - --http-address=0.0.0.0:4180
        - --email-domain=*
        - --cookie-secure=false
        - --redirect-url=http://128.224.207.103:32712/oauth2/callback
        - --reverse-proxy=true
        - --set-xauthrequest=true
        env:
        - name: OAUTH2_PROXY_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: client-id
        - name: OAUTH2_PROXY_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: client-secret
        - name: OAUTH2_PROXY_COOKIE_SECRET
          valueFrom:
            secretKeyRef:
              name: oauth2-proxy-secret
              key: cookie-secret
        ports:
        - containerPort: 4180

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-proxy
  namespace: demo
spec:
  selector:
    app: oauth2-proxy
  ports:
  - port: 4180
    targetPort: 4180

# =========================
# App1 UI (Status Panel)
# =========================
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app1-ui
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>SSO Demo - App 1 (Status Panel)</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <style>
        :root { --bg:#0f172a; --card:#111827; --text:#e5e7eb; --muted:#94a3b8; --accent:#38bdf8; --ok:#22c55e; --warn:#f59e0b; }
        body { margin:0; font-family: ui-sans-serif,system-ui,-apple-system,Segoe UI,Roboto; background:linear-gradient(135deg,#0f172a,#111827); color:var(--text); }
        .container { max-width: 960px; margin: 40px auto; padding: 16px; }
        .header { display:flex; align-items:center; justify-content:space-between; }
        .title { font-size:28px; font-weight:700; letter-spacing:0.3px; }
        .user { font-size:14px; color:var(--muted); }
        .grid { margin-top:20px; display:grid; grid-template-columns: repeat(3, 1fr); gap:16px; }
        .card { background: rgba(255,255,255,0.04); border:1px solid rgba(255,255,255,0.08); border-radius:16px; padding:18px; box-shadow: 0 10px 30px rgba(0,0,0,0.25); backdrop-filter: blur(4px); }
        .label { font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:0.1em; }
        .value { font-size:22px; margin-top:6px; font-weight:600; }
        .ok { color: var(--ok); } .warn { color: var(--warn); } .accent { color: var(--accent); }
        .footer { margin-top:22px; font-size:12px; color:var(--muted); }
        a { color: var(--accent); text-decoration: none; }
      </style>
    </head>
    <body>
      <div class="container">
        <div class="header">
          <div class="title">App 1 · Status Panel</div>
          <div class="user" id="user">Loading user…</div>
        </div>
        <div class="grid">
          <div class="card"><div class="label">Cluster</div><div class="value accent">demo</div></div>
          <div class="card"><div class="label">Auth</div><div class="value ok" id="auth">Authenticated</div></div>
          <div class="card"><div class="label">Latency (ms)</div><div class="value" id="lat">-</div></div>
          <div class="card"><div class="label">Services</div><div class="value">oauth2-proxy, nginx, app1-ui, app2-ui</div></div>
          <div class="card"><div class="label">Session</div><div class="value" id="session">-</div></div>
          <div class="card"><div class="label">Next App</div><div class="value"><a href="/app2/">Open App 2 →</a></div></div>
        </div>
        <div class="footer">
          One login (GitHub) works for both UIs: <a href="/app1/">/app1</a> and <a href="/app2/">/app2</a>.
        </div>
      </div>
      <script>
        const t0 = performance.now();
        fetch('/oauth2/userinfo', {credentials:'include'})
          .then(r => r.json())
          .then(j => {
            document.getElementById('user').textContent = `Signed in as ${j.user || j.email || j.preferred_username || 'unknown'}`;
            document.getElementById('session').textContent = j.email ? ('email: ' + j.email) : (j.user || '—');
            const t1 = performance.now();
            document.getElementById('lat').textContent = Math.round(t1 - t0);
          })
          .catch(() => { document.getElementById('user').textContent = 'Not signed in'; });
      </script>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-ui
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app1-ui
  template:
    metadata:
      labels:
        app: app1-ui
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web
        configMap:
          name: app1-ui

---
apiVersion: v1
kind: Service
metadata:
  name: app1-ui
  namespace: demo
spec:
  selector:
    app: app1-ui
  ports:
  - port: 80
    targetPort: 80

# =========================
# App2 UI (Notes Board)
# =========================
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app2-ui
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>SSO Demo - App 2 (Notes Board)</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <style>
        :root { --bg:#0b1020; --panel:#12193a; --paper:#fff3cd; --text:#0b1020; --ink:#1f2937; --muted:#93a4bf; --link:#60a5fa; }
        body { margin:0; font-family: Inter, ui-sans-serif, system-ui; background: radial-gradient(600px circle at 20% 10%, #1c2757 0, transparent 40%), radial-gradient(800px circle at 80% 0%, #162046 0, transparent 40%), #0b1020; }
        .wrap { max-width: 980px; margin: 38px auto; padding: 0 16px; color: #e5e7eb; }
        .top { display:flex; align-items:center; justify-content:space-between; }
        h1 { margin:0; font-size:28px; }
        .user { color:#cbd5e1; font-size:14px; }
        .board { margin-top:22px; display:grid; grid-template-columns: repeat(3, 1fr); gap:16px; }
        .note { background: var(--paper); color: var(--text); border-radius: 10px; padding: 14px; box-shadow: 0 8px 25px rgba(0,0,0,0.25), inset 0 0 0 1px rgba(0,0,0,0.06); }
        .note h3 { margin: 0 0 8px 0; font-size: 16px; color: var(--ink); }
        .note p { margin: 0; font-size: 14px; }
        .links { margin-top: 18px; font-size: 14px; }
        a { color: var(--link); text-decoration: none; }
      </style>
    </head>
    <body>
      <div class="wrap">
        <div class="top">
          <h1>App 2 · Notes Board</h1>
          <div class="user" id="user">Loading user…</div>
        </div>
        <div class="board">
          <div class="note"><h3>Welcome</h3><p>This board shows SSO is active.</p></div>
          <div class="note"><h3>One Cookie</h3><p>Login on App 1 works here too.</p></div>
          <div class="note"><h3>Try It</h3><p><a href="/app1/">Open App 1</a> (no re-login)</p></div>
        </div>
        <div class="links">
          Need to sign out? Hit <a href="/oauth2/sign_out">/oauth2/sign_out</a> (clears session).
        </div>
      </div>
      <script>
        fetch('/oauth2/userinfo', {credentials:'include'})
          .then(r => r.json())
          .then(j => {
            document.getElementById('user').textContent =
              `Signed in as ${j.user || j.email || j.preferred_username || 'unknown'}`;
          })
          .catch(() => { document.getElementById('user').textContent = 'Not signed in'; });
      </script>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2-ui
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2-ui
  template:
    metadata:
      labels:
        app: app2-ui
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web
        configMap:
          name: app2-ui

---
apiVersion: v1
kind: Service
metadata:
  name: app2-ui
  namespace: demo
spec:
  selector:
    app: app2-ui
  ports:
  - port: 80
    targetPort: 80

# =========================
# Mainframe UI at "/"
# =========================
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mainframe-ui
  namespace: demo
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8" />
      <title>SSO Demo — Mainframe</title>
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <style>
        :root { --bg:#0f1226; --panel:#0b1020; --card:#111936; --text:#e5e7eb; --muted:#93a4bf; --a:#60a5fa; --a2:#22c55e; }
        * { box-sizing: border-box; }
        body { margin:0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto;
               background: radial-gradient(900px 600px at 20% 0%, #1a2350 0, transparent 40%),
                           radial-gradient(900px 600px at 80% 0%, #142043 0, transparent 40%),
                           var(--bg);
               color: var(--text); }
        .wrap { max-width: 980px; margin: 36px auto; padding: 0 16px; }
        .top  { display:flex; align-items:center; justify-content:space-between; gap:16px; }
        h1 { margin:0; font-size:28px; letter-spacing:.2px; }
        .user { color: var(--muted); font-size:14px; }
        .grid { margin-top:22px; display:grid; grid-template-columns: repeat(2, 1fr); gap:18px; }
        .card {
          background: linear-gradient(180deg, rgba(255,255,255,.06), rgba(255,255,255,.03));
          border:1px solid rgba(255,255,255,.08); border-radius:16px; padding:20px;
          box-shadow: 0 10px 30px rgba(0,0,0,.35);
          transition: transform .15s ease, box-shadow .15s ease, border-color .15s ease;
        }
        .card:hover { transform: translateY(-2px); border-color: rgba(96,165,250,.6); }
        .card h3 { margin:0 0 8px 0; font-size:18px; }
        .card p  { margin:0 0 12px 0; color: var(--muted); font-size:14px; }
        .btn {
          display:inline-block; padding:10px 14px; border-radius:12px; text-decoration:none;
          background:#0b5bb5; color:white; font-weight:600;
        }
        .btn.secondary { background:#0f7a3b; }
        .links { margin-top:20px; font-size:14px; color:var(--muted); }
        .links a { color: var(--a); text-decoration:none; }
        .row { display:flex; gap:12px; flex-wrap:wrap; }
      </style>
    </head>
    <body>
      <div class="wrap">
        <div class="top">
          <h1>SSO Mainframe</h1>
          <div class="user" id="user">Checking authentication…</div>
        </div>

        <div class="grid">
          <div class="card">
            <h3>App 1 · Status Panel</h3>
            <p>Clean dashboard-style UI. Protected by the same GitHub login.</p>
            <a class="btn" href="/app1/">Open App 1 →</a>
          </div>
          <div class="card">
            <h3>App 2 · Notes Board</h3>
            <p>Sticky-notes style board. Opens without re-login (SSO).</p>
            <a class="btn secondary" href="/app2/">Open App 2 →</a>
          </div>
        </div>

        <div class="links">
          <div class="row">
            <a href="/oauth2/sign_out">Sign out</a>
            <span>•</span>
            <a href="/oauth2/userinfo" target="_blank" rel="noreferrer">View /oauth2/userinfo</a>
          </div>
        </div>
      </div>

      <script>
        fetch('/oauth2/userinfo', { credentials: 'include' })
          .then(r => r.ok ? r.json() : Promise.reject())
          .then(j => {
            const who = j.user || j.email || j.preferred_username || j.name || 'unknown';
            document.getElementById('user').textContent = `Signed in as ${who}`;
          })
          .catch(() => { document.getElementById('user').textContent = 'Not signed in (refresh should redirect)'; });
      </script>
    </body>
    </html>

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainframe-ui
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mainframe-ui
  template:
    metadata:
      labels:
        app: mainframe-ui
    spec:
      containers:
      - name: web
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web
        configMap:
          name: mainframe-ui

---
apiVersion: v1
kind: Service
metadata:
  name: mainframe-ui
  namespace: demo
spec:
  selector:
    app: mainframe-ui
  ports:
  - port: 80
    targetPort: 80

# =========================
# Public NGINX (NodePort)
# =========================
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: demo
data:
  default.conf: |
    server {
      listen 80;

      # --- oauth2-proxy endpoints ---
      location /oauth2/ {
        proxy_pass       http://oauth2-proxy.demo.svc.cluster.local:4180;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      location /oauth2/callback {
        proxy_pass       http://oauth2-proxy.demo.svc.cluster.local:4180/oauth2/callback;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
      location = /oauth2/auth {
        proxy_pass       http://oauth2-proxy.demo.svc.cluster.local:4180/oauth2/auth;
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Identity headers from oauth2-proxy (since --set-xauthrequest=true)
        auth_request_set $auth_user  $upstream_http_x_auth_request_user;
        auth_request_set $auth_email $upstream_http_x_auth_request_email;
        add_header X-User  $auth_user;
        add_header X-Email $auth_email;
      }

      # --- PROTECT "/" and serve Mainframe UI ---
      location = / {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/start;

        proxy_pass       http://mainframe-ui.demo.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # --- App 1 ---
      location /app1/ {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/start;

        rewrite ^/app1/(.*)$ /$1 break;
        proxy_pass       http://app1-ui.demo.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }

      # --- App 2 ---
      location /app2/ {
        auth_request /oauth2/auth;
        error_page 401 = /oauth2/start;

        rewrite ^/app2/(.*)$ /$1 break;
        proxy_pass       http://app2-ui.demo.svc.cluster.local:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
      }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: demo
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 32712
  type: NodePort
